export default {
    "username": "Brukernavn",
    "password": "Passord",
    "userType": "Brukertype",
    "app": "App",

    "upload_user_image": "Last opp bilde av bruker",
    "choose_phone": "Velg bilde",
    "desktop": "Desktopversjon",
    "both": "Begge",
    "name": "Navn",
    "company_name": "Selskapsnavn",
    "address": "Adresse",
    "post_code": "Postnummer",
    "email": "E-post",
    "mobile": "Mobilnummer",
    "org_nr": "Organisasjonsnummer",
    "contact_person": "Kontaktperson",
    "phone": "Telefonnummer",
    "company_contact": "Kontaktperson hos selskapet",
    "company_email_settings": "e-postinnstilling",
    "company_email_name": "Navn på E-post avsender",
    "company_email": "Avsenders e-postadresse",
    "title": "Tittel",
    "back_to": "Tilbake til",
    "thirdpaty_type": "Ansvarsområde",
    "is_created": "er opprettet",
    "is_updated": "har blitt oppdatert",
    "is_active": "Aktiv",
    "is_deleted": "er slettet",
    "projects": "Prosjekter",
    "projects_setting": "Projekt Innstillinger",
    "services": "Tjenester",
    "checklist_template": "Sjekklistemaler",
    "building_supplier": "Boligleverandør",

    "third_party": "Foretak",
    "email_template": "E-post maler",
    "documentions": "Dokumenter",
    "contacts": "Kontakter",
    "my_team": "Mitt team",
    "company_profile": "Firma profil",
    "users": "Brukere",
    "my_profile": "Min profil",
    "dashboard": "Dashbord",
    "edit": "Rediger",
    "required": "Kreves",
    "yes": "Ja",
    "no": "Nei",
    "submit": "Lagre",
    "add_to_project_by_default": "Bli lagt på prosjektopprettelse",
    "description": "Beskrivelse",
    "rate": "Pris",
    "add_new": "Legg til",
    "photo": "Bilde",
    "choose_contact": "Velg kontakt"


}